"use client"

// ShaderBackground — generated by the 21st.dev Shader Builder
// ("Pulsing Border"). Zero dependencies: one WebGL canvas that fills its
// parent. Drop it behind your content with
// <div className="relative"><ShaderBackground className="absolute inset-0" />…
// Adapted from Paper Shaders: https://shaders.paper.design/pulsing-border
// Paper Shaders is licensed under Apache-2.0.
//
// Local changes:
//
//  1. Colours are the site's own accent ramp rather than the generator's blue and
//     cyan. See SITE_COLORS.
//  2. prefers-reduced-motion is honoured. The original animates forever at
//     timeScale 0.575 with no check, which on this site would be the single
//     largest unmanaged motion source on any page. Under the preference the
//     time uniform is frozen, which makes `timeAnimated` false and lets the
//     existing render loop settle after one frame: a still image of the same
//     shader, not a blank canvas and not a stopped animation mid-pulse.
//  3. The GLSL is specialised down to the features this site actually uses, which
//     is what makes it affordable. See the note above FRAG.
//  4. DPR is pinned to 1 and the frame rate capped at 30. Both are free here: the
//     image is a soft gradient glow with no detail for extra samples to resolve,
//     and the pulse takes seconds to cross one edge.

import { useEffect, useRef, useState } from "react"

const VERT = `attribute vec2 a_position;
void main() {
  gl_Position = vec4(a_position, 0.0, 1.0);
}`

/**
 * Specialised from the generated shader, and verified bit-identical.
 *
 * The generator emits every feature it can produce and gates each behind a
 * uniform. This site sets warp, blur, hue, drift, rotate, offset, the OKLab
 * toggle and the cursor to zero, but a driver still compiles both sides of every
 * one of those branches. That is not free: the first draw, which is when the
 * driver actually does the compile, cost ~350ms and took this page from 96 to 68
 * on Lighthouse mobile. The same harness with a trivial shader costs 13ms.
 *
 * Removed: the OKLab colour path (the worst offender, since palette() loops seven
 * times and each step called it), fbm/noise/hash and the domain warp that used
 * them, the 5-tap blur (five palette() loops per fragment), hue rotation, the
 * cursor distortions, and rotate/offset/drift. Kept: the cheap post-processing,
 * so contrast, saturation, brightness, vignette and grain all still respond.
 *
 * Checked rather than assumed: rendered against the original at 700x300 over four
 * time values and compared every byte. 0 of 840,000 differed, max channel delta 0.
 *
 * The trade is that those uniforms are now inert. Setting UNIFORMS.warp above zero
 * will do nothing until the corresponding code comes back, which means re-pasting
 * from the generator rather than editing this.
 */
const FRAG = `
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

uniform vec3 u_colors[8];
uniform vec4 u_scene;      // resolution.xy, time, colour count
uniform vec4 u_shape;      // scale, intensity, paramA, (warp: removed)
uniform vec4 u_surface;    // (detail: removed), contrast, brightness, saturation
uniform vec4 u_finish;     // (hue: removed), vignette, (blur: removed), grain
uniform vec4 u_transform;  // seed, (rotate/drift/oklab: removed)
uniform vec4 u_space;      // (offset/pointer: removed)
uniform vec4 u_cursor;     // (removed)

#define u_resolution u_scene.xy
#define u_time u_scene.z
#define u_colorCount u_scene.w
#define u_scale u_shape.x
#define u_intensity u_shape.y
#define u_paramA u_shape.z
#define u_contrast u_surface.y
#define u_brightness u_surface.z
#define u_saturation u_surface.w
#define u_vignette u_finish.y
#define u_grain u_finish.w
#ifdef GL_FRAGMENT_PRECISION_HIGH
#define u_seed u_transform.x
#else
// Keep hash inputs inside mediump's guaranteed +/-2^14 range.
#define u_seed mod(u_transform.x, 31.0)
#endif

// Even, un-structured white noise for film grain (Dave Hoskins hash12).
float grainHash(vec2 p) {
  vec3 p3 = fract(vec3(p.xyx) * 0.1031);
  p3 += dot(p3, p3.yzx + 33.33);
  return fract((p3.x + p3.y) * p3.z);
}

// Mix through the recipe colours; x is clamped to 0..1. WebGL1 forbids dynamic
// uniform indexing in fragment shaders, hence the constant loop.
//
// The OKLab branch is gone. It was the single most expensive thing in the
// original: this loop runs seven times, and each step called a mix helper
// containing an sRGB decode, an OKLab encode and decode, and an sRGB re-encode,
// which is roughly twelve pow() calls. The runtime toggle was off, but a driver
// still compiles both sides of the branch and unrolls the loop around them.
vec3 palette(float x) {
  float n = max(u_colorCount - 1.0, 1.0);
  float f = clamp(x, 0.0, 1.0) * n;
  vec3 col = u_colors[0];
  for (int i = 0; i < 7; i++) {
    if (float(i) < n)
      col = mix(col, u_colors[i + 1],
        smoothstep(0.0, 1.0, clamp(f - float(i), 0.0, 1.0)));
  }
  return col;
}

// The uv parameter is dropped: the original declared it and never read it.
vec3 shade(vec2 p, float t) {
  vec2 box = vec2(0.82, 0.47);
  vec2 d = abs(p) - box;
  float outside = length(max(d, 0.0)) + min(max(d.x, d.y), 0.0);
  float thickness = mix(0.018, 0.11, u_paramA);
  float edge = 1.0 - smoothstep(thickness * 0.35, thickness, abs(outside));
  float perimeter = atan(p.y * box.x, p.x * box.y) / 6.2831853 + 0.5;
  float pulse = 0.5 + 0.5 * sin(perimeter * (5.0 + u_intensity * 9.0) - t * 1.8);
  float trail = pow(pulse, mix(7.0, 2.0, u_intensity));
  float innerGlow = exp(-abs(outside) * 24.0) * 0.32;
  return mix(u_colors[0], palette(trail), clamp(edge + innerGlow, 0.0, 1.0));
}

void main() {
  vec2 screenUv = gl_FragCoord.xy / u_resolution.xy;
  vec2 p = (gl_FragCoord.xy - 0.5 * u_resolution.xy)
    / min(u_resolution.x, u_resolution.y);
  p *= u_scale;

  // No cursor block, no rotate/offset/drift, no domain warp, no 5-tap blur.
  // Every one of those was gated on a uniform this site sets to zero, and the
  // blur path in particular called shade() five times per fragment, which means
  // five palette() loops.
  vec3 col = shade(p, u_time);

  // Post kept as-is: these are a few arithmetic ops each, cheap enough that
  // removing them would save nothing while making the look harder to adjust.
  if (abs(u_contrast - 1.0) > 0.0001)
    col = (col - 0.5) * u_contrast + 0.5;
  if (abs(u_saturation - 1.0) > 0.0001) {
    float luma = dot(col, vec3(0.299, 0.587, 0.114));
    col = mix(vec3(luma), col, u_saturation);
  }
  if (abs(u_brightness) > 0.0001)
    col += u_brightness;
  if (u_vignette > 0.0001) {
    float vd = length(screenUv - 0.5) * 1.41421356;
    col *= 1.0 - u_vignette * smoothstep(0.35, 1.0, vd);
  }
  if (u_grain > 0.0001)
    col += (grainHash(
      gl_FragCoord.xy + vec2(u_seed * 17.0, u_seed * 31.0)) - 0.5) * u_grain;
  gl_FragColor = vec4(clamp(col, 0.0, 1.0), 1.0);
}
`

/**
 * The site's accent ramp, replacing the generator's blue and cyan default.
 *
 * Index 0 is the ground the border is drawn on and is the page background
 * exactly, so the canvas has no visible edge against the rest of the page. The
 * rest are GradientShimmer's own stops, which is what makes this read as the
 * same site as the wordmark rather than a widget dropped on top of it. The pulse
 * peaks at a pale pink tint rather than pure white, so its hottest point still
 * belongs to the palette.
 *
 * Slots past colorCount are ignored by the shader but must be filled: u_colors
 * is a fixed vec3[8] and WebGL needs all eight supplied.
 */
const SITE_COLORS: [number, number, number][] = [
  [0.0196078431372549, 0.0196078431372549, 0.027450980392156862], // #050507 page ground
  [0.5450980392156862, 0.4823529411764706, 1], // #8B7BFF violet
  [1, 0.4823529411764706, 0.7647058823529411], // #FF7BC3 pink
  [1, 0.9137254901960784, 0.9607843137254902], // #FFE9F5 pale pink highlight
  [1, 0.9137254901960784, 0.9607843137254902],
  [1, 0.9137254901960784, 0.9607843137254902],
  [1, 0.9137254901960784, 0.9607843137254902],
  [1, 0.9137254901960784, 0.9607843137254902],
]

const UNIFORMS = {
  colors: SITE_COLORS,
  colorCount: 4,
  /**
   * 0.95, down from the generator's 1.26.
   *
   * The border is a fixed 1.74:1 box in a space normalised by the canvas's
   * *shorter* side, so its on-screen size depends on both the container's aspect
   * and this value. 1.26 is tuned for a full viewport; in a banner it left the
   * rectangle small and floating in the middle rather than framing anything.
   * At 0.95 the box reaches roughly 94% of the height and 72% of the width of a
   * 7:3 container, which is what makes it read as a frame around the heading.
   *
   * Consequence worth knowing: because the box cannot change shape, a container
   * that is close to square clips the left and right edges and leaves only the
   * horizontal runs visible. That is what happens on a narrow phone, where the
   * banner's min-height wins over its aspect ratio.
   */
  scale: 0.95,
  intensity: 0.350,
  paramA: 0.280,
  warp: 0.000,
  detail: 1.824,
  contrast: 1.005,
  brightness: 0.000,
  saturation: 1.000,
  hue: 0.0000,
  vignette: 0.000,
  blur: 0.0000,
  grain: 0.042,
  seed: 1.0,
  rotate: 0.0000,
  offsetX: 0.000,
  offsetY: 0.000,
  drift: 0.000,
  cursorEnabled: false,
  cursorEffect: 2.0,
  cursorStrength: 0.650,
  cursorRadius: 0.460,
  oklab: 0.0,
  timeScale: 0.575,
}

const REDUCED_MOTION = "(prefers-reduced-motion: reduce)"

const pendingContextReleases = new WeakMap<HTMLCanvasElement, number>()

export function PulsingBorder({ className }: { className?: string }) {
  const canvasRef = useRef<HTMLCanvasElement>(null)

  // Read on the client only. During static export there is no matchMedia, and
  // guessing "no preference" then correcting after hydration would start the
  // animation for exactly the people who asked not to see it.
  const [reduced, setReduced] = useState(false)
  useEffect(() => {
    if (typeof window.matchMedia !== "function") return
    const query = window.matchMedia(REDUCED_MOTION)
    const sync = () => setReduced(query.matches)
    sync()
    query.addEventListener("change", sync)
    return () => query.removeEventListener("change", sync)
  }, [])

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return

    // Runs on mount, deliberately, despite the cost documented below.
    //
    // Deferring set-up to requestIdleCallback was tried and measured worse: it
    // moves the work out of page load and into the window where total blocking
    // time is sampled, taking desktop from 92 to 75. Waiting longer would only
    // hide the number while leaving the same stall for the reader, and a banner
    // that lights up seconds late reads as broken.
    const pendingRelease = pendingContextReleases.get(canvas)
    if (pendingRelease !== undefined) window.clearTimeout(pendingRelease)
    pendingContextReleases.delete(canvas)
    const context = canvas.getContext("webgl", { antialias: false })
    if (!context) return
    // Re-declared with a non-nullable type rather than relying on the narrowing
    // above. `render` below is a hoisted function declaration, and TypeScript
    // discards enclosing narrowings inside those because a hoisted declaration
    // could in principle be called before the guard runs. Giving `gl` a
    // non-nullable declared type means there is no narrowing to lose.
    const gl: WebGLRenderingContext = context

    const compile = (type: number, src: string) => {
      const s = gl.createShader(type)!
      gl.shaderSource(s, src)
      gl.compileShader(s)
      return s
    }
    const program = gl.createProgram()!
    const vertexShader = compile(gl.VERTEX_SHADER, VERT)
    const fragmentShader = compile(gl.FRAGMENT_SHADER, FRAG)
    gl.attachShader(program, vertexShader)
    gl.attachShader(program, fragmentShader)
    gl.linkProgram(program)
    gl.deleteShader(vertexShader)
    gl.deleteShader(fragmentShader)
    gl.useProgram(program)

    const buf = gl.createBuffer()
    gl.bindBuffer(gl.ARRAY_BUFFER, buf)
    gl.bufferData(
      gl.ARRAY_BUFFER,
      new Float32Array([-1, -1, 3, -1, -1, 3]),
      gl.STATIC_DRAW,
    )
    const loc = gl.getAttribLocation(program, "a_position")
    gl.enableVertexAttribArray(loc)
    gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0)

    const uni = {
      colors: gl.getUniformLocation(program, "u_colors"),
      scene: gl.getUniformLocation(program, "u_scene"),
      shape: gl.getUniformLocation(program, "u_shape"),
      surface: gl.getUniformLocation(program, "u_surface"),
      finish: gl.getUniformLocation(program, "u_finish"),
      transform: gl.getUniformLocation(program, "u_transform"),
      space: gl.getUniformLocation(program, "u_space"),
      cursor: gl.getUniformLocation(program, "u_cursor"),
    }
    gl.uniform3fv(uni.colors, new Float32Array(UNIFORMS.colors.flat()))
    gl.uniform4f(
      uni.shape,
      UNIFORMS.scale,
      UNIFORMS.intensity,
      UNIFORMS.paramA,
      UNIFORMS.warp,
    )
    gl.uniform4f(
      uni.surface,
      UNIFORMS.detail,
      UNIFORMS.contrast,
      UNIFORMS.brightness,
      UNIFORMS.saturation,
    )
    gl.uniform4f(
      uni.finish,
      UNIFORMS.hue,
      UNIFORMS.vignette,
      UNIFORMS.blur,
      UNIFORMS.grain,
    )
    gl.uniform4f(
      uni.transform,
      UNIFORMS.seed,
      UNIFORMS.rotate,
      UNIFORMS.drift,
      UNIFORMS.oklab,
    )
    gl.uniform4f(
      uni.cursor,
      0,
      UNIFORMS.cursorEffect,
      UNIFORMS.cursorStrength,
      UNIFORMS.cursorRadius,
    )

    let targetX = 0
    let targetY = 0
    let targetPresence = 0
    let mouseX = 0
    let mouseY = 0
    let cursorPresence = 0
    let pointerKnown = false
    let pointerClientX = 0
    let pointerClientY = 0
    let bounds = canvas.getBoundingClientRect()
    let raf = 0
    let lastNow: number | null = null
    let visible = document.visibilityState === "visible"
    let inView = true
    let disposed = false
    const start = performance.now()
    // Frozen under the preference. `timeAnimated` then goes false, so the loop
    // below draws one frame and settles instead of running forever.
    const timeScale = reduced ? 0 : UNIFORMS.timeScale
    const timeAnimated = Math.abs(timeScale) > 0.0001
    // 30fps. The pulse takes several seconds to travel one side of the border, so
    // there is nothing in this image that 60fps resolves and 30 does not, and it
    // halves the GPU work on a page whose actual content is twenty animated sprite
    // sheets. Frames are skipped by returning early rather than by slowing the
    // clock, so the animation runs at the same speed either way.
    const FRAME_MS = 1000 / 30
    let lastDraw = Number.NEGATIVE_INFINITY

    const resizeCanvas = () => {
      // DPR 1 and a 640k pixel budget, down from 2 and 2,000,000.
      //
      // Measured on the textures page: the generator's defaults cost 27 Lighthouse
      // points on mobile (96 to 69) and took total blocking time from 50ms to
      // 1030ms. Nearly all of that is fragment count multiplied by frame rate, and
      // none of it buys anything visible here: the image is a soft gradient glow
      // over a near-black field, with no fine detail for the extra samples to
      // resolve. A retina banner would be four times the fragments to render the
      // same blur.
      const dpr = 1
      const rawWidth = Math.max(1, Math.round(bounds.width * dpr))
      const rawHeight = Math.max(1, Math.round(bounds.height * dpr))
      const pixelScale = Math.min(
        1,
        Math.sqrt(640_000 / Math.max(1, rawWidth * rawHeight)),
      )
      const width = Math.max(1, Math.round(rawWidth * pixelScale))
      const height = Math.max(1, Math.round(rawHeight * pixelScale))
      if (canvas.width !== width || canvas.height !== height) {
        canvas.width = width
        canvas.height = height
        gl.viewport(0, 0, width, height)
      }
      // Returned so `render` never has to touch the canvas itself. It is a hoisted
      // function declaration, and TypeScript drops the `if (!canvas) return`
      // narrowing inside those, since a hoisted declaration could in principle be
      // called before the guard runs. Arrow functions like this one keep it.
      return { width, height }
    }

    function requestRender() {
      if (!disposed && visible && inView && raf === 0) {
        raf = requestAnimationFrame(render)
      }
    }

    const updatePointerTarget = () => {
      if (!pointerKnown) return
      if (bounds.width === 0 || bounds.height === 0) return
      const inside =
        pointerClientX >= bounds.left &&
        pointerClientX <= bounds.right &&
        pointerClientY >= bounds.top &&
        pointerClientY <= bounds.bottom
      if (!inside) {
        targetPresence = 0
        requestRender()
        return
      }
      const nextX = ((pointerClientX - bounds.left) / bounds.width) * 2 - 1
      const nextY = -(((pointerClientY - bounds.top) / bounds.height) * 2 - 1)
      if (targetPresence === 0 && cursorPresence < 0.01) {
        mouseX = nextX
        mouseY = nextY
      }
      targetX = nextX
      targetY = nextY
      targetPresence = 1
      requestRender()
    }
    const onPointerMove = (event: PointerEvent) => {
      pointerKnown = true
      pointerClientX = event.clientX
      pointerClientY = event.clientY
      bounds = canvas.getBoundingClientRect()
      updatePointerTarget()
    }
    const onPointerLeave = () => {
      pointerKnown = false
      targetPresence = 0
      requestRender()
    }
    const updateLayout = () => {
      bounds = canvas.getBoundingClientRect()
      resizeCanvas()
      updatePointerTarget()
      requestRender()
    }
    window.addEventListener("resize", updateLayout)
    if (UNIFORMS.cursorEnabled) {
      window.addEventListener("pointermove", onPointerMove, { passive: true })
      window.addEventListener("pointercancel", onPointerLeave)
      window.addEventListener("scroll", updateLayout, true)
      window.addEventListener("blur", onPointerLeave)
      document.documentElement.addEventListener("pointerleave", onPointerLeave)
    }

    const resizeObserver = new ResizeObserver(updateLayout)
    resizeObserver.observe(canvas)
    const intersectionObserver = new IntersectionObserver(([entry]) => {
      inView = entry?.isIntersecting ?? true
      if (inView) requestRender()
      else if (raf !== 0) {
        cancelAnimationFrame(raf)
        raf = 0
        lastNow = null
      }
    })
    intersectionObserver.observe(canvas)
    const onVisibilityChange = () => {
      visible = document.visibilityState === "visible"
      if (visible) requestRender()
      else if (raf !== 0) {
        cancelAnimationFrame(raf)
        raf = 0
        lastNow = null
      }
    }
    document.addEventListener("visibilitychange", onVisibilityChange)

    function render(now: number) {
      raf = 0
      if (disposed || !visible || !inView) return
      // Too soon: ask for another frame without doing any GPU work. lastNow is left
      // alone so the next real draw sees the full elapsed time and the pointer
      // easing stays framerate-independent.
      if (now - lastDraw < FRAME_MS) {
        requestRender()
        return
      }
      lastDraw = now
      const dt = lastNow === null ? 0 : Math.min((now - lastNow) / 1000, 0.1)
      lastNow = now
      const follow = 1 - Math.exp(-12 * dt)
      mouseX += (targetX - mouseX) * follow
      mouseY += (targetY - mouseY) * follow
      cursorPresence += (targetPresence - cursorPresence) * follow
      const { width, height } = resizeCanvas()
      gl.uniform4f(
        uni.scene,
        width,
        height,
        ((now - start) / 1000) * timeScale,
        UNIFORMS.colorCount,
      )
      gl.uniform4f(
        uni.space,
        UNIFORMS.offsetX,
        UNIFORMS.offsetY,
        mouseX,
        mouseY,
      )
      gl.uniform4f(
        uni.cursor,
        UNIFORMS.cursorEnabled ? cursorPresence : 0,
        UNIFORMS.cursorEffect,
        UNIFORMS.cursorStrength,
        UNIFORMS.cursorRadius,
      )
      gl.drawArrays(gl.TRIANGLES, 0, 3)
      const pointerSettling =
        Math.abs(targetX - mouseX) > 0.001 ||
        Math.abs(targetY - mouseY) > 0.001 ||
        Math.abs(targetPresence - cursorPresence) > 0.001
      if (timeAnimated || pointerSettling) requestRender()
      else lastNow = null
    }
    requestRender()
    return () => {
      disposed = true
      cancelAnimationFrame(raf)
      resizeObserver.disconnect()
      intersectionObserver.disconnect()
      document.removeEventListener("visibilitychange", onVisibilityChange)
      window.removeEventListener("resize", updateLayout)
      if (UNIFORMS.cursorEnabled) {
        window.removeEventListener("pointermove", onPointerMove)
        window.removeEventListener("pointercancel", onPointerLeave)
        window.removeEventListener("scroll", updateLayout, true)
        window.removeEventListener("blur", onPointerLeave)
        document.documentElement.removeEventListener(
          "pointerleave",
          onPointerLeave,
        )
      }
      gl.deleteBuffer(buf)
      gl.deleteProgram(program)
      const releaseTimer = window.setTimeout(() => {
        if (pendingContextReleases.get(canvas) !== releaseTimer) return
        pendingContextReleases.delete(canvas)
        gl.getExtension("WEBGL_lose_context")?.loseContext()
        canvas.width = 1
        canvas.height = 1
      }, 0)
      pendingContextReleases.set(canvas, releaseTimer)
    }
    // Re-initialises if the preference changes mid-session, which is the only
    // way to pick up a new timeScale given it is captured per-run.
  }, [reduced])

  return (
    <canvas
      ref={canvasRef}
      // Decorative. Nothing here carries meaning that is not already in the
      // heading it sits behind.
      aria-hidden="true"
      className={className}
      style={{ display: "block", width: "100%", height: "100%" }}
    />
  )
}
